application:
  name: digital-monster-mongodb
  project: digital-monster-api
  organization: QoveryCommunity
databases:
- type: mongodb
  version: "3.6"
  name: digimon
routers:
- name: main
  routes:
  - application_name: digital-monster-mongodb
    paths:
    - /
