application:
  name: digimon-api
  project: digital-monster-api
  publicly_accessible: true
  organization: QoveryCommunity
databases:
- type: mongodb
  version: "3.6"
  name: my-mongodb-7274989
routers:
- name: main
  routes:
  - application_name: digimon-api
    paths:
    - /
