---
application:
  name: "digital-monster-api"
  project: "digital-monster-api"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "digimon"
  version: "3.6"
routers:
- name: "main-digital-monster-api"
  routes:
  - application_name: "digital-monster-api"
    paths:
    - "/"
