application:
  name: digital-monster-api
  project: digital-monster-api
  publicly_accessible: true
databases:
- type: mongodb
  version: 3.6
  name: my-mongo
routers:
- name: main
  routes:
  - application_name: digital-monster-api
    paths:
    - /