application:
  name: digital-monster-api
  project: digital-monster
  publicly_accessible: true
databases:
  - type: mongodb
    version: 4.2
    name: digimon
routers:
  - name: main
    routes:
      - application_name: digital-monster-api
        paths:
          - /
