version: '3.4'
services:
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: denopassword
      POSTGRES_USER: deno
      POSTGRES_DB: denoapp
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - app

  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command:
      ['run', '--allow-net', '--allow-env', '--allow-read', 'src/server.ts']
    working_dir: /app
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - app

networks:
  app:

volumes:
  postgres:
