export interface DigimonProfile {
  name: string;
  level: Level;
  type: Type;
  attribute: Attribute;
  field?: Field[];
  group?: Group;
  abilities: { name: string; description: string | null };
  profile: { image: string; description: string | null };
  profile_img: string;
}

export interface DigimonSchema {
  _id: { $oid: string };
  name: string;
  level: Level;
  type: Type;
  attribute: Attribute;
  field?: Field[];
  group?: Group;
  abilities: { name: string; description: string | null };
  profile: { image: string; description: string | null };
  weight: string[];
}

type Level =
  | "Baby I"
  | "Baby II"
  | "Child"
  | "Adult"
  | "Perfect"
  | "Ultimate"
  | "Armor"
  | "Hybrid"
  | "Unknown";

type Type =
  | "9000"
  | "Aerial Assault"
  | "Alien"
  | "Amphibian"
  | "Ancient"
  | "Ancient Aquatic Beast Man"
  | "Ancient Beast"
  | "Ancient Bird"
  | "Ancient Bird Man"
  | "Ancient Crustacean"
  | "Ancient Dragon"
  | "Ancient Dragon Man"
  | "Ancient Fish"
  | "Ancient Holy Knight"
  | "Ancient Insect"
  | "Ancient Mutant"
  | "Ancient Mythical Beast"
  | "Ancient Ore"
  | "Ancient Plant"
  | "Angel"
  | "Ankylosaur"
  | "Aquatic"
  | "Aquatic Beast Man"
  | "Aquatic Mammal"
  | "Archangel"
  | "Armed Reconnaissance"
  | "Armor"
  | "Artificial Fallen Angel"
  | "Avatar"
  | "Baby Dragon"
  | "Base Defense"
  | "Beast"
  | "Beast Dragon"
  | "Beast Knight"
  | "Beast Man"
  | "Bewitching Beast"
  | "Bewitching Bird"
  | "Bird"
  | "Bird Dragon"
  | "Bird Man"
  | "Braun"
  | "Bulb"
  | "Card"
  | "Ceratopsian"
  | "Cherub"
  | "Chick"
  | "Commander"
  | "Composite"
  | "Crustacean"
  | "Cyborg"
  | "Dark Dragon"
  | "Dark Knight"
  | "Demon Beast"
  | "Demon Dragon"
  | "Demon God"
  | "Demon Lord"
  | "Demon Man"
  | "Devil"
  | "Dinosaur"
  | "Dominion"
  | "Dragon"
  | "Dragon Man"
  | "Dragon Warrior"
  | "Earth Dragon"
  | "Enhancement"
  | "Espionage"
  | "Evil Dragon"
  | "Fairy"
  | "Fallen Angel"
  | "Flame"
  | "Flame Dragon"
  | "Food"
  | "Galaxy"
  | "Ghost"
  | "Giant Bird"
  | "God Beast"
  | "God man"
  | "Grappling"
  | "Ground Assault"
  | "Holy Beast"
  | "Holy Bird"
  | "Holy Dragon"
  | "Holy Knight"
  | "Holy Sword"
  | "Hybrid"
  | "Ice-snow"
  | "Information Gathering"
  | "Insect"
  | "Insectivorious Plant"
  | "Invade"
  | "Larva"
  | "LCD"
  | "Lesser"
  | "Light Dragon"
  | "Machine"
  | "Machine Dragon"
  | "Magic Warrior"
  | "Magic Knight"
  | "Major"
  | "Mammal"
  | "Marine Animal"
  | "Marine Man"
  | "Mine"
  | "Mineral"
  | "Minor"
  | "Mollusk"
  | "Monk"
  | "Mother Ship"
  | "Musical Instrument"
  | "Mutant"
  | "Mythical Beast"
  | "Mythical Dragon"
  | "No Data"
  | "Ocean Dragon"
  | "Oni"
  | "Ophan"
  | "Ore"
  | "Parasite"
  | "Perfect"
  | "Plant"
  | "Plesiosaur"
  | "Power"
  | "Pterosaur"
  | "Puppet"
  | "Rare Animal"
  | "Reptile"
  | "Reptile Man"
  | "Rock"
  | "Rock Dragon"
  | "Seed"
  | "Seraph"
  | "Skeleton"
  | "Sky Dragon"
  | "Slime"
  | "Small Angel"
  | "Small Bird"
  | "Small Devil"
  | "Small Dragon"
  | "Smoke"
  | "Spirit"
  | "Stegosaur"
  | "Super Major"
  | "Synthetic Beast"
  | "Tathāgata"
  | "Toy"
  | "Tropical Fish"
  | "Unbalanced"
  | "Undead"
  | "Unique"
  | "Unanalyzable"
  | "Unknown"
  | "Virtue"
  | "Warrior"
  | "Weapon"
  | "Wicked God";

type Attribute = "Vaccine" | "Data" | "Virus" | "Free" | "Variable" | "Unknown";

type Field =
  | "Nature Spirits"
  | "Deep Savers"
  | "Nightmare Soldiers"
  | "Wind Guardians"
  | "Metal Empire"
  | "Unknown"
  | "Dark Area"
  | "Virus Busters"
  | "Dragon's Roar"
  | "Jungle Troopers";

type Group =
  | "Artifical Digimon"
  | "BAN-TYO"
  | "Big Death-Stars"
  | "Crack Team"
  | "D-Brigade"
  | "Dark Masters"
  | "Digimon King"
  | "Deva"
  | "Four Great Dragons"
  | "Four Holy Beasts"
  | "Gaia Origin"
  | "Legend-Arms"
  | "Olympus Twelve"
  | "Royal Knights"
  | "Seven Great Demon Lords"
  | "Three Gods of Destruction"
  | "Three Great Angels"
  | "Three Head Officers"
  | "Three Musketeers"
  | "Ultimate 4"
  | "Warrior Ten";