name: ci
on:
  push:
    branches: [main]
  pull_request:

env:
  IMAGE_NAME: ricoledan/digimon-api

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        deno: ['v1.x', 'nightly']
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Setup repo
      - uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@c7d7968ad4a59c159a777f79adddad6872ee8d96
        with:
          deno-version: ${{ matrix.deno }}

      - name: Cache Dependencies
        run: deno run -A --unstable drakefile.ts cache

      - name: Run Tests
        run: deno run -A --unstable drakefile.ts test

  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ricoledan/digimon-api:$(date +%s)
